name: FloatingText
main: glorydark.floatingtext.FloatingTextMain
author: glorydark
version: "1.2.3"
description: FloatingText
api: "1.0.0"
load: POSTWORLD
softdepend:
  - Tips
  - MemoriesOfTime-GameCore